import { useEffect, useState } from 'react';
import { apiRequest } from './api';
import type { ConnectedAccount, PlatformCapability } from './data';
import Icon from './Icon';

export default function ConnectedPlatforms() {
  const [platforms, setPlatforms] = useState<PlatformCapability[]>([]); const [accounts, setAccounts] = useState<ConnectedAccount[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const load = () => { setLoading(true); Promise.all([apiRequest<PlatformCapability[]>('/api/v1/platforms'), apiRequest<ConnectedAccount[]>('/api/v1/platforms/accounts')]).then(([nextPlatforms, nextAccounts]) => { setPlatforms(nextPlatforms); setAccounts(nextAccounts); }).catch((caught) => setError(caught instanceof Error ? caught.message : 'Unable to load connected platforms.')).finally(() => setLoading(false)); };
  useEffect(load, []);
  const connect = async (platform: string) => { setBusy(platform); setError(''); try { const account = await apiRequest<ConnectedAccount>('/api/v1/platforms/accounts/connect', { method: 'POST', body: JSON.stringify({ platform }) }); setAccounts((current) => [account, ...current.filter((item) => item.id !== account.id)]); setPlatforms((current) => current.map((item) => item.platform === platform ? { ...item, connected: true } : item)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to connect platform.'); } finally { setBusy(''); } };
  const disconnect = async (id: number, platform: string) => { setBusy(platform); setError(''); try { await apiRequest(`/api/v1/platforms/accounts/${id}`, { method: 'DELETE' }); setAccounts((current) => current.filter((item) => item.id !== id)); setPlatforms((current) => current.map((item) => item.platform === platform ? { ...item, connected: false } : item)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to disconnect platform.'); } finally { setBusy(''); } };
  if (loading) return <div className="library-empty"><div><Icon name="platforms" size={24} /></div><strong>Loading connected platforms…</strong></div>;
  return <section className="platforms-page"><div className="platforms-header"><div><p className="eyebrow">Advertising connections</p><h1>Connected platforms</h1><p className="subtitle">Connect the accounts you manage and review each platform’s capabilities.</p></div><span className="review-badge"><i />Sandbox adapters</span></div>{error && <div className="auth-message error" role="alert">{error}</div>}<div className="platform-grid">{platforms.map((platform) => { const account = accounts.find((item) => item.platform === platform.platform); return <article className="platform-card" key={platform.platform}><div className="platform-card-top"><div className={`platform-logo logo-${platform.platform}`}><Icon name="platforms" size={21} /></div><span className={account ? 'connection-status connected' : 'connection-status'}><i />{account ? 'Connected' : 'Not connected'}</span></div><h2>{platform.label}</h2><p>{platform.sandbox ? 'Deterministic sandbox adapter for local end-to-end testing.' : 'Live platform connection.'}</p><div className="capability-list"><span className={platform.supports_oauth ? 'supported' : ''}>OAuth</span><span className={platform.supports_video ? 'supported' : ''}>Video</span><span className={platform.supports_metrics ? 'supported' : ''}>Metrics</span><span className={platform.supports_pause ? 'supported' : ''}>Pause</span></div>{account ? <div className="connected-account"><div><strong>{account.name}</strong><small>{account.external_account_id} · {account.currency}</small></div><button onClick={() => disconnect(account.id, platform.platform)} disabled={busy === platform.platform}>Disconnect</button></div> : <button className="button button-primary connect-button" onClick={() => connect(platform.platform)} disabled={busy === platform.platform}>{busy === platform.platform ? 'Connecting…' : 'Connect sandbox account'} {!busy && <Icon name="arrow" size={15} />}</button>}</article>; })}</div><div className="platform-note"><Icon name="spark" size={17} /><p><strong>Credentials stay on the server.</strong> Sandbox access tokens are encrypted at rest and are never returned to the browser. Live OAuth can be enabled when approved Meta and Google developer credentials are configured.</p></div></section>;
}
